name: QA

on:
    pull_request:
        branches:
            - release/*

jobs:
    backend:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                # Since using PHPUnit 8 we can only support PHP7.2 and up.
                php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2']
        name: PHP ${{ matrix.php }}
        steps:
            -   uses: actions/checkout@v2

            # https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none # disable xdebug, pcov

            -   run: composer validate --strict
            -   run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
            -   run: composer install --prefer-dist --no-progress --no-suggest --no-scripts
            -   if: always()
                run: composer run-script lint
            -   if: always()
                run: composer run-script analysis -- --no-suggestions --output-format=github
            -   if: always()
                run: composer run-script test
